spring:
  application:
    name: Spring Boot Actuator Info

server:
    servlet:
      context-path: /api/v1
    shutdown: graceful

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true
    git:
      mode: full
info:
  name: ${spring.application.name}
  description: This project is configured to expose several helpful Info endpoints with Spring Boot Actuator.
